module Common

let buildPredictionData (basicPage:Models.PreparedBasicInfos) (templates:List<Models.PreparedTemplates>) =
    let buildRow (template:Models.PreparedTemplates) = 
        Models.PredictionData.Row(
            basicPage.Page.Structure01,
            basicPage.Page.Structure02,
            basicPage.Page.Structure03,
            basicPage.Page.Structure04,
            basicPage.Page.Structure05,
            basicPage.Page.Structure06,
            basicPage.Page.Structure07,
            basicPage.Structure01_words,
            basicPage.Structure02_words,
            basicPage.Structure03_words,
            basicPage.Structure04_words,
            basicPage.Structure05_words,
            basicPage.Structure06_words,
            basicPage.Structure07_words,
            template.Page.Count,
            template.Page.Structure01,
            template.Page.Structure02,
            template.Page.Structure03,
            template.Page.Structure04,
            template.Page.Structure05,
            template.Page.Structure06,
            template.Page.Structure07,
            template.Page.Structure08,
            template.Page.Category01,
            template.Page.Category02,
            template.Page.Category03,
            template.Page.Category04,
            template.Page.Category05,
            template.Page.Category06,
            template.Page.Category07,
            template.Page.Category08,
            template.Page.Category09,
            template.Page.Category10,
            template.Page.Category11,
            template.Page.Category12,
            template.Page.Category13,
            template.Page.Category14,
            template.Page.Category15,
            template.Page.Category16,
            template.Page.Category17,
            template.Page.Category18,
            template.Page.Category19,
            template.Page.Category_not_available,
            template.Structure01_words,
            template.Structure02_words,
            template.Structure03_words,
            template.Structure04_words,
            template.Structure05_words,
            template.Structure06_words,
            template.Structure07_words,
            template.Structure08_words)
    
    let data = templates |> List.map buildRow |> Models.PredictionData
    data